version: "3.8"

services:
  www:
        build: .
        ports:
            - "8007:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - proyectofinal
        networks:
            - default
  proyectofinal:
    image: mysql:latest
    container_name: proyectofinal
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: maye
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - my-db:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
     - "8008:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: proyectofinal
      PMA_USER: root
      PMA_PASSWORD: root
volumes:
  my-db:
